### ISSUE TITLE
characteristic was supplied illegal value: number 10 exceeded minimum of 17.

### ISSUE THREAD

**Issue by NikDevx** [Tommrodrigues/homebridge-web-thermostat#17]
Hello 
Thanks for your plugin!

How I can fix it?

`[homebridge-web-thermostat] This plugin generated a warning from the characteristic 'Target Temperature': characteristic was supplied illegal value: number 10 exceeded minimum of 17. See https://git.io/JtMGR for more info.`

It's coming from here

```
        this.service
            .getCharacteristic(Characteristic.TargetTemperature)
            .on('set', this.setTargetTemperature.bind(this))
            .setProps({
                minValue: this.minTemp,
                maxValue: this.maxTemp,
                minStep: this.minStep
            })
```

**Comment by NikDevx** [comment]
No longer support?

**Comment by phenotypic** [comment]
Hi there, do you receive this error upon startup?

Please could you also include your `config.json` for this accessory.

Looking at the Homebridge API for [Target Temperature](https://developers.homebridge.io/#/characteristic/TargetTemperature) you can see that the minimum value is `10`. This plugin sets the minimum temperature to `15`, so there should be no conflict.

Have you maybe changed `minTemp` in your `config.json`?

**Comment by NikDevx** [comment]
> Please could you also include your `config.json` for this accessory.

```
    "accessories": [
        {
            "accessory": "Thermostat",
            "name": "AC",
            "apiroute": "http://raspberrypi.local:8085",
            "pollInterval": 60,
            "minTemp": 17,
            "maxTemp": 30,
            "minStep": 1,
            "timeout": 15000
        }
    ]
```

**Comment by NikDevx** [comment]
Hello
I receive this upon startup.

**Comment by NikDevx** [comment]
And also I getting error when api route has http instead https
I changed request method function from `_httpRequest:`  to `request.get`
You can see it in my fork https://github.com/NikDevx/homebridge-web-thermostat/blob/master/index.js

**Comment by phenotypic** [comment]
I was not able to reproduce the error using the same configuration as you (with the exception of the `apiroute` field).

As such, I believe the error is either with the data your API is returning, or with modifications you have made to your fork of the plugin.

To be sure, please include a sample of what your API is responding. Also try the same configuration using this original version of the plugin, not your fork.

**Comment by NikDevx** [comment]
I getting status from json via get request http://raspberrypi.local:8085/status/
Here is no value under 17 in Target Temperature

`{"targetHeatingCoolingState":0,"targetTemperature":28,"currentHeatingCoolingState":0,"currentTemperature":24}`

**Comment by NikDevx** [comment]
My logs with debug

```
[26.04.2021, 13:13:18] [Кондиционер] Device response: {"targetHeatingCoolingState":0,"targetTemperature":28,"currentHeatingCoolingState":0,"currentTemperature":24}
[26.04.2021, 13:13:18] [Кондиционер] Updated TargetTemperature to: 28
[26.04.2021, 13:13:18] [Кондиционер] Updated CurrentTemperature to: 24
[26.04.2021, 13:13:18] [Кондиционер] Updated TargetHeatingCoolingState to: 0
[26.04.2021, 13:13:18] [Кондиционер] Updated CurrentHeatingCoolingState to: 0
[26.04.2021, 13:13:55] [Кондиционер] Getting status: http://raspberrypi.local:8085/status
```


Errors

```
[26.04.2021, 13:13:03] [homebridge-web-thermostat] This plugin generated a warning from the characteristic 'Target Temperature': characteristic was supplied illegal value: number 10 exceeded minimum of 17. See https://git.io/JtMGR for more info.
[26.04.2021, 13:13:03] [homebridge-web-thermostat] Error: 
    at TargetTemperature.Characteristic.characteristicWarning (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2038:105)
    at TargetTemperature.Characteristic.validateUserInput (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1946:16)
    at TargetTemperature.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1499:21)
    at step (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
    at Object.next (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:124:57)
    at /usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:113:16)
    at TargetTemperature.Characteristic.handleGetRequest (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Characteristic.js:656:24)
    at TargetTemperature.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2103:22)
```

**Comment by NikDevx** [comment]
I installed the new version and has the same error upon startup.

**Comment by phenotypic** [comment]
Unfortunately, I was once again unable to replicate your error. Here are the relevant versions:

- node `16.0.0`
- homebridge `1.3.4`
- homebridge-web-thermostat `1.3.7`

I simulated your API locally and used this configuration:

```
{
    "accessory": "Thermostat",
    "name": "AC",
    "apiroute": "http://[::]:8000",
    "pollInterval": 60,
    "minTemp": 17,
    "maxTemp": 30,
    "minStep": 1,
    "timeout": 15000
}
```

This was the API response (`http://[::]:8000/status`):

```
{
    "targetHeatingCoolingState": 0,
    "targetTemperature": 28,
    "currentHeatingCoolingState": 0,
    "currentTemperature": 24
}
```

No errors were generated on startup, and I was able to successfully change the target state and temperature:

```
[26/04/2021, 14:22:19] [AC] Set targetHeatingCoolingState to: 1
[26/04/2021, 14:22:24] [AC] Set targetTemperature to: 29.0
[26/04/2021, 14:22:30] [AC] Set targetTemperature to: 27.0
[26/04/2021, 14:22:31] [AC] Set targetHeatingCoolingState to: 0
```

I'm afraid there's not much more I can do on my end in terms of debugging, as everything seems to be working as expected.

You might want to look into communication problems with your API, and/or any modifications you have made to your fork of the plugin.

**Comment by NikDevx** [comment]
Hm... Very strange.
Thank for you help.
I will try to change my api
